(defpackage :parmenides
  (:nicknames :parm :pa)
  (:use :cl)
  (:export #:add-cslot
           #:add-slot
           #:add-to-facet
           #:add-to-facet-demons
           #:add-to-value
           #:add-to-slot
           #:pa-class-of
           #:pframep
           #:classp
           #:slotp
           #:facetedp
           #:frame-instance-p
           #:copy-frame
           #:def-frame
           #:def-frame*
           #:frame
           #:get-cslot
           #:add-to-cslot
           #:set-cslot
           #:get-facet
           #:get-facet-demons
           #:get-generic-value
           #:get-immediate-facet
           #:get-immediate-slot
           #:get-immediate-value
           #:get-slot
           #:get-slot-names
           #:get-value
           #:get-value-demons
           #:immediate-isas
           #:instance-names-of
           #:instances-of
           #:set-instances-of
           #:inverse-isas
           #:isa-instance
           #:isa-p
           #:isas
           #:local-p
           #:make-frame
           #:make-frame0
           #:fast-make-frame0
           #:remove-frame
           #:set-facet
           #:set-facet-demons
           #:set-slot
           #:set-value
           #:set-value-demons
           #:do-facets
           #:isa-or-instance
           #:save-frame
           #:pp-frame
           #:define-facet-getter
           #:define-facet-setter
           #:define-facet-accessors
           #:ml-format
           #:ml-error
           #:ml-cerror
           #:get-free-frame
           #:release-frame
           #:with-all-subinstances-of
           #:with-all-subclasses-of
           #:delete-class-instance
           #:relation
           #:make-relation
           #:relation-combination-type
           #:relation-slots-inherited.value
           #:relation-has-inverses
           #:relation-inverse-name
           #:framename
           #:slotname
           #:facetname
           #:frame
           #:snum
           #:facetnum
           #:newval
           #:oldval
           #:*read-only*
           #:!!inheritance-type
           #:!!inheritance-link
           #:*parmenides-terse*
           #:set-language))
