(defpackage #:frulekit
  (:use #:cl #:parmenides)
  (:export
   #:rule
   #:rule*
   #:build-rule
   #:build-rule*
   #:pp-rule
   #:pp-instant
   #:ith-wme
   #:pp-wme
   #:pp-wmes
   #:pp-ith-wme
   #:pp-wm
   #:save-wme
   #:save-ith-wme
   #:save-wm
   #:wm
   #:set-wm
   #:add-to-wm
   #:def-cr-strategy
   #:def-complex-cr-strategy
   #:pr-switches
   #:re-init-trace
   #:$disj
   #:$disj-nums
   #:start
   #:literalize
   #:$make
   #:$fast-make
   #:$make-named
   #:$remove
   #:$remove-keep
   #:$modify
   #:$modify-demons
   #:$modify-in-place
   #:excise
   #:add-frame
   #:whynot
   #:matches
   #:d-in-instants
   #:halt
   #:rbreak
   #:cont
   #:run
   #:back
   #:init-rete
   #:clear-net
   #:compile-nodes
   #:compile-rhses
   #:compile-all
   #:inhibit-rules
   #:uninhibit-rules
   #:$modify-num
   #:var
   #:<>
   #:end-rhs
   #:def-inverse-action
   #:var-in-instant
   #:in-wm-p
   ;; Frame and structure access
   #:rk-rule-lhs
   #:rk-rule-rhs
   #:rk-rule-beliefs
   #:rk-rule-pname
   #:rk-rule-extra-test
   #:rk-rule-num-tests
   #:wme
   #:wme-%time
   #:wme-%created
   #:wme-%class
   #:token-contents
   #:token-match-count
   #:token-bindval
   #:instant-token
   #:instant-prod
   #:instant-sortedwmes
   ;; Global variables
   #:*cr-strategy*
   #:*mea*
   #:*lex*
   #:*full-cr*
   #:narrow-down-mea
   #:narrow-down-lex
   #:narrow-down-test-class
   #:num-tests
   #:num-checks
   #:narrow-down-wme-class
   #:*rule-names*
   #:*record-level*
   #:*max-back*
   #:*pause-every-cycle*
   #:*conflict-set*
   #:*instant*
   #:*trace-fire*
   #:*trace-match*
   #:*trace-unmatch*
   #:*trace-add*
   #:*trace-delete*
   #:*trace-cr*
   #:*trace-cycle*
   #:*trace-modify*
   #:*rulekit-terse*
   #:*refract*
   #:*full-wmeprint*
   #:*number-wmes*
   #:*agenda-loaded*
   #:*cycle*
   ;; Programmer's symbols (not documented - some should be)
   #:rk-rule-pnode
   #:rk-rule-left-access
   #:rk-rule-inscount
   #:rk-rule-break
   #:reverse-improper
   #:rk-variablep
   #:wmep
   #:def-beta-var
   #:*non-deletions*
   #:*agenda*
   #:*dont-warn-lisp-checks*
   #:*no-literalize*
   ;; User-accessible agenda functions, macros and variables
   ;; documented in the user's manual.
   #:r-linear
   #:r-cycle
   #:r-priority
   #:r-agenda
   #:create-new-agenda
   #:cont-agenda
   #:add-rule
   #:add-rules
   #:make-bucket
   #:add-buckets
   #:add-bucket
   #:add-new-bucket
   #:delete-rules
   #:delete-buckets
   #:delete-bucket
   #:get-bucket
   #:compile-extra-tests
   #:rk-rule-add
   #:rk-rule-del
   #:rk-rule-bucket-add
   #:rk-rule-bucket-del
   #:rk-rule-ktest
   #:rk-rule-bucket
   #:rk-rule-instants
   #:!trace-test
   #:!trace-act
   #:!trace-agenda
   #:!!control
   #:*AGENDA*
   ;; User-accessible trace functions, macros and variables documented
   ;; in the user's manual.
   #:var-names-of
   #:var-in-instant
   #:instant-wmes-of
   #:prod-of
   #:give-additions-on-cycle
   #:give-deletions-on-cycle
   #:give-matches
   #:give-firings
   #:give-next-matches
   #:give-next-firings
   #:give-matches-on-cycle
   #:give-firings-on-cycle
   #:give-named-matches
   #:give-un-matches-on-cycle
   #:give-named-firings
   #:lhs-of
   #:rhs-of
   #:prod-responsible-for
   #:possible-prods-responsible-for
   #:in-wmp
   #:give-instant
   #:give-negs
   #:rule-rhs-of
   ;; Patty Cheng's additions
   #:Give-firing-on-cycle
   #:Give-linear-trace
   #:Give-prod-name
   ;; Def-frame accessors
   #:Wme-%matches
   #:Wme-%firings
   #:Wme-%label
   ))
